name: Build Gradle

on:
  workflow_call:

jobs:
  build_gradle:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: "Building and pushing the image to Container Registry"
        uses: ./
        with:
          gcloud_service_key: ${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }}
          registry: gcr.io
          project_id: certain-reducer-330917
          image_name: hello-world-by-push-to-gcr
          image_tag: ${{ github.sha }}, ${{ github.sha }}
          dockerfile: ./Dockerfile
          context: ./
          target: build

