name: Build Gradle

on:
  workflow_call:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.3'
          cache: 'gradle'
      - name: Run build
        run: |
          ./gradlew clean build
      - name: Archive test report
        uses: actions/upload-artifact@v3
        with:
          name: Test report
          path: build/reports/tests/test
