name: deploy

on:
  workflow_call:
    inputs:
      gcp-project-id:
        required: true
        type: string
      gcp-project-number:
        required: true
        type: number

permissions:
  contents: read

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - uses: 'actions/setup-java@v3'
        with:
          distribution: 'temurin'
          java-version: '17.0.3'
          cache: 'gradle'

      - uses: 'gradle/gradle-build-action@v2'
        with:
          arguments: build

      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@v1'

      - name: 'Containerize'
        run: docker build -t 'sample-app' .

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/${{ inputs.gcp-project-number }}/locations/global/workloadIdentityPools/test-pool/providers/my-provider'
          service_account: 'sample-service-account@${{ inputs.gcp-project-id }}.iam.gserviceaccount.com'

      - uses: 'docker/login-action@v1'
        with:
          registry: 'europe-west3-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: 'Tag image'
        run: docker tag 'sample-app' 'europe-west3-docker.pkg.dev/${{ inputs.gcp-project-id }}/sample-app/sample-app'

      - name: 'Push image to the repository'
        run: docker push 'europe-west3-docker.pkg.dev/${{ inputs.gcp-project-id }}/sample-app/sample-app'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'sample-app'
          image: 'europe-west3-docker.pkg.dev/${{ inputs.gcp-project-id }}/sample-app/sample-app:latest'
          region: 'europe-west3'

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
