name: CI
on: [push]
jobs:
  build:
    uses: ./.github/workflows/build.yml
  push-container:
    name: "Building and pushing the image"
    runs-on: ubuntu-latest
    steps:
        - name: "Building and pushing the image to Container Registry"
          uses: ./
          with:
            gcloud_service_key: ${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }}
            registry: gcr.io
            project_id: certain-reducer-330917
            image_name: hello-world-by-push-to-gcr
            image_tag: ${{ github.sha }}, ${{ github.sha }}
            dockerfile: ./Dockerfile
            context: ./
            target: build

